### ISSUE TITLE
在挂载Google Drive时出现链接错误，无法获取code，大家有这样的情况嘛？

### ISSUE THREAD

**Issue by ke-xi** [shirooo39/MiXLab#13]
@shirooo39 大佬帮忙康康嘛！
![プロペ](https://pic2.acg-moe.com/images/2021/08/28/jMh2n.png "プロペ")
![プロペ](https://pic2.acg-moe.com/images/2021/08/28/jMxWU.png "プロペ")

**Comment by shirooo39** [comment]
你好! 我不会说中文，我使用的是在线翻译器。如果我的中文说得不好，我很抱歉。

我刚刚试了一下，它对我来说是有效的。
![image](https://user-images.githubusercontent.com/38461122/131235715-4666e249-3aef-4054-85b5-6f774b606b1a.png)

我不知道你是如何得到404错误的，但我认为这一定是与谷歌有关的问题。
你能在不同的浏览器上试一下吗？

如果你知道如何使用rclone，我强烈建议你用rclone代替。
安装Google Drive并将下载路径指向那里，有时可能会导致文件损坏。

**Comment by ke-xi** [comment]
#

> 你好! 我不会说中文，我使用的是在线翻译器。如果我的中文说得不好，我很抱歉。
> 
> 我刚刚试了一下，它对我来说是有效的。
> ![image](https://user-images.githubusercontent.com/38461122/131235715-4666e249-3aef-4054-85b5-6f774b606b1a.png)
> 
> 我不知道你是如何得到404错误的，但我认为这一定是与谷歌有关的问题。
> 
> 你能在其他浏览器上试试吗？
> (也许在Microsoft Edge上试试？)
> 顺便说一下，我使用的是Firefox 91.0.2版（截至目前的最新版本）。
> 
> 安装Google Drive并将下载路径指向那里，有时可能会导致文件损坏。
> 如果你知道如何使用rclone，我强烈建议你用rclone代替。

Thank you. The problem has been solved
