### ISSUE TITLE
Do you know how to bypass 750gb upload limit of google drive? If you do then please do tell me.

### ISSUE THREAD

**Issue by klvilo** [shirooo39/MiXLab#16]

**Comment by shirooo39** [comment]
Yes, I do know how to bypass that 750GB upload limit, it's not a new knowledge either.
But the thing is, you'd still gonna get hit by the hard 2TB limit. This is also accounting server-side copy.

btw I'm still working on a simple python command that I'm trying to write myself and it seems to be working... on Windows.
hopefully it'd be easy to move onto Google Colab.

the auto-rclone doesn't seem to work anymore, so I'm writing my own code.

**Comment by AndreVuillemot160** [comment]
Eh... Y'know there's gclone as well, and PR in rclone repo which adds Service Accounts support I think.

**Comment by shirooo39** [comment]
> 
> 
> Eh... Y'know there's gclone as well, and PR in rclone repo which adds Service Accounts support I think.

I've tried all of those and nothing work.
it could be just me, or those projects are actually no longer working.

the manual rclone is the only way.
add a bit of for looping and voila.

**Comment by AndreVuillemot160** [comment]
WELLLLLLLLLL, I use my own custom up to date gclone. And everything works fine for me. I just used the AutoRclone tho for service accounts generation.

**Comment by shirooo39** [comment]
@klvilo I came up with my own script, which you can find in here https://github.com/shirooo39/GSAclone

do note that the script is far from perfect.
feel free to use it, or just walk away.
