### ISSUE TITLE
JDownloader is not displayed on WebUI

### ISSUE THREAD

**Issue by kakasplatt** [shirooo39/MiXLab#3]
Since yesterday afternoon, JDownloader's connection to WebUI has stopped working when using Colab. It works normally when using JDownloader on my PC, because I thought it might be a WebUI problem or something, but it doesn't seem to be ...

Does anyone else have this problem?

**Comment by shirooo39** [comment]
It's fixed and you should be able to use it now.
Just tried it a couple of days ago and everything was working fine.

Give it a try
if it does work now for you, we can close this.

**Comment by shirooo39** [comment]
> 
> 
> Since yesterday afternoon, JDownloader's connection to WebUI has stopped working when using Colab. It works normally when using JDownloader on my PC, because I thought it might be a WebUI problem or something, but it doesn't seem to be ...
> 
> Does anyone else have this problem?

It's fixed and you should be able to use it now.
Just tried it a couple of days ago and everything was working fine.

Give it a try
if it does work now for you, we can close this.
