### ISSUE TITLE
Issue about mounting rclone remote failed

### ISSUE THREAD

**Issue by rrfqi** [shirooo39/MiXLab#30]
I've never get any problem until last night I got this error, anyone encounter this problem same as me?

![Screenshot 2023-03-15 at 11-33-24 Google Colaboratory(1)](https://user-images.githubusercontent.com/35894106/225207977-882514c0-7b9c-44a1-bdde-39025af73370.png)

**Comment by tmatzxzone** [comment]
same even on the latest update a few minutes ago

**Comment by rrfqi** [comment]
> rclone latest version cant mount, fix it by roll back to Rclone v1.61.1

I've figured it out yesterday, you just have to install fuse3 then it will run normally

**Comment by shirooo39** [comment]
I wasn't getting the same issue but fuse just refuses to mount my OneDrive drive.
it dit get mounted, but there's no file or folder to list.  
looking up the forum, it's indeed something related to fuse3 that seems not being installed(?)

anyway, I've added the fuse3 dep to install
![image](https://user-images.githubusercontent.com/38461122/225829650-25fa9961-aa54-4d3c-9ade-3e931fbd4404.png)
can you give it a try and see if it's working?

**Comment by tmatzxzone** [comment]
yep it's work now
