### ISSUE TITLE
Can't load qbittorent UI

### ISSUE THREAD

**Issue by de2apandi** [shirooo39/MiXLab#5]
Hello admin i got error when use qbittorent web ui, i got error 
like this  **Unauthorized**   when after start qbittorent and click the webhost

please fix  thanks

**Comment by shirooo39** [comment]
I'm not sure yet what's wrong with qBittorrent (could be config issue? idk) but in the mean time, there are other alternatives to qBittorrent that you can use.

aria2 is highly recommended as it can handle torrent as well.

**Comment by shirooo39** [comment]
> 
> 
> Hello admin i got error when use qbittorent web ui, i got error
> like this **Unauthorized** when after start qbittorent and click the webhost
> 
> please fix thanks

I'm not sure yet what's wrong with qBittorrent (could be config issue? idk) but in the mean time, there are other alternatives to qBittorrent that you can use.

aria2 is highly recommended as it can handle torrent as well.

**Comment by shirooo39** [comment]
I've just edited the configuration file and it should now be working again.
